module.exports = [
	{
		_id: "5cf0e67b19dd1cff656529d2",
		__v: 0,
		data: {
			sections: [],
			_id: "5cf0e67b19dd1cff656529d2",
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Terry Virgo",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Terry Virgo founded the New Frontiers group of churches, a network of over 1,500 churches planted throughout the world. In this episode he talks about his own conversion, his relationship with Martyn Lloyd-Jones, people who have influenced him and principles on which the New Frontiers group of churches was established.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "gPVCjCAOG0c",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/gPVCjCAOG0c/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/gPVCjCAOG0c",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560347831335.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-02-09",
					placeholder: "Enter publish date",
					required: true,
				},
			],
		},
		lastModified: 1560347868928,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d013d89ed2e4a252462ece8",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Rico Tice",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Rico Tice is Senior Minister (Evangelism) at All Souls Langham Place, co-author of Christianity Explored and co-developer of the Christianity Explored and Life Explored courses. \n\nIn this episode he talks about his own story and the stories of people who influenced him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "MByRJkmO4vk",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/MByRJkmO4vk/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/MByRJkmO4vk",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560362348640.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-01-05",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d013d89ed2e4a252462ece8",
		},
		lastModified: 1560362377845,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d013e45ed2e4a252462eced",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Pete Woodcock",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Pete Woodcock is senior pastor of Cornerstone Church, Kingston and an author. In this episode he talks about his own story and stories of people who influenced him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "PVLn3-ql4r4",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/PVLn3-ql4r4/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/PVLn3-ql4r4",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560362560779.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-01-13",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d013e45ed2e4a252462eced",
		},
		lastModified: 1560362565594,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d013fb5ed2e4a252462ecf5",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Glen Scrivener",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Glen Scrivener is an innovative evangelist becoming more and more conspicuous through his work in apologetics, his videos, his books, his blogs with The Gospel Coalition, his podcast and his work with SpeakLife. We had the privilege of talking with him recently about his story on our podcast.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "J1-LP_5Rs0A",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/J1-LP_5Rs0A/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/J1-LP_5Rs0A",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560362928224.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-01-26",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d013fb5ed2e4a252462ecf5",
		},
		lastModified: 1560362933260,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d014081ed2e4a252462ecfe",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Trevor Archer",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Trevor Archer, London Director of the FIEC (Fellowship of Independent Evangelical Churches) tells his own fantastic story and of people who have influenced him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "DdPhmYSxk1Y",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/DdPhmYSxk1Y/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/DdPhmYSxk1Y",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560363131891.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-02-24",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d014081ed2e4a252462ecfe",
		},
		lastModified: 1560363137016,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d01422fed2e4a252462ed03",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Joe Boot",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Dr Joe Boot is Pastor of Westminster Chapel, Toronto; founder of the Ezra Institute for Contemporary Christianity; and Head of Public Theology at Christian Concern. In this episode he talks about his own story and the stories of people who influenced him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "Q9sauas11gA",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/Q9sauas11gA/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/Q9sauas11gA",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560363557661.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-03-12",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d01422fed2e4a252462ed03",
		},
		lastModified: 1560363567014,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d0220f468e4fd3ff83eb1a0",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Richard Borgonon",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Richard Borgonon is the man behind The Word One to One - a course of notes that are being used internationally to help people discuss what the Bible *actually* says about the gospel of Jesus Christ.\n\nIn this episode Richard tells us the story of how they came to be written, and many stories of how they're being used.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "xyVVE_xUCmw",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/xyVVE_xUCmw/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/xyVVE_xUCmw",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560420593186.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-03-25",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0220f468e4fd3ff83eb1a0",
		},
		lastModified: 1560420596612,
		dateCreated: 1671487897506,
	},
	{
		_id: "5d02215e68e4fd3ff83eb1a7",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Bill Edgar",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Bill Edgar is the author of Created and Creating (IVP/Apollos 2017 - 'An important book on a topic that, for Western Christians, has never been so crucial' - Tim Keller), Schaeffer on the Christian Life (Crossway 2013 - 'Francis Schaeffer comes alive in Edgar's objective but affectionate portrait' - Os Guinness), and Reasons of the Heart (P&R 2012).\n\nHe is also professor of apologetics at Westminster Theological Seminary and associate professor at the Faculté Jean Calvin.\n\nIn this podcast he talks about his conversion story, his relationships with Francis Schaeffer, Os Guinness, Ed Clowney and others, and reflects on the challenges and opportunities of our own moment.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "0zxqR55Q0GQ",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/0zxqR55Q0GQ/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/0zxqR55Q0GQ",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560420686662.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-04-06",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d02215e68e4fd3ff83eb1a7",
		},
		lastModified: 1560420702062,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d0224fa1a519e4080891125",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Roger Carswell",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Roger Carswell is one of Britain's best respected and most warmly loved evangelists. Author of And Some Evangelists, Evangelistic Preaching, Before Your Say I Don't Believe, Grill A Christian and many other books and tracts, he is in great demand as a preacher of the gospel. \n\nWe had a wonderful time talking with him about his own story, about people who've inspired him and about the opportunities for the church in our time. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "JNd2umR3wkQ",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/JNd2umR3wkQ/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/JNd2umR3wkQ",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560421593051.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-04-21",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0224fa1a519e4080891125",
		},
		lastModified: 1560421626224,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d0225821a519e408089112a",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Andrea Williams",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Andrea Williams is CEO of Christian Concern: a unique ministry in our time, supporting Christians when the world's intolerance of their stand for gospel simplicity and truth has resulted in legal condemnation.\n\nListen as we hear her story and the stories of her own inspiration. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "DfvbEGaW-24",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/DfvbEGaW-24/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/DfvbEGaW-24",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560421693955.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-05-15",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0225821a519e408089112a",
		},
		lastModified: 1560421762916,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d0226311a519e408089112f",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Garry Williams",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Garry Williams is Director of Pastors' Academy at London Seminary and author of His Love Endures Forever (IVP and Crossway) and Silent Witnesses (Banner of Truth).\n\nIn this podcast he talks about his own testimony and about heroes from church history who've inspired him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "Al53H1vm-2U",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/Al53H1vm-2U/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/Al53H1vm-2U",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560421877068.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-06-09",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0226311a519e408089112f",
		},
		lastModified: 1560421937352,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d0226b81a519e4080891134",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "William Taylor",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "William Taylor is Rector of St Helen's Bishopsgate, London, and is the author of several books including Understanding the Times, Revolutionary Sex, and Revolutionary Work.\n\nIn this episode of the Christian Heritage London podcast he shares his own testimony and tells stories of heroes and of extraordinary lessons he's learned.\n",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "U-0Fvf9tG8Q",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/U-0Fvf9tG8Q/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/U-0Fvf9tG8Q",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560422028160.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2018-12-08",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0226b81a519e4080891134",
		},
		lastModified: 1560422072421,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d0227961a519e4080891139",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Gavin Peacock",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Gavin Peacock began playing football professionally as a teenager, beginning a career during which he would play for Newcastle United, QPR and Chelsea.\n\nHis approach and insight into the game was ratified by a follow up career as a BBC pundit and presenter. \n\nHe has since retrained as a pastor; studying at Cambridge, UK and Calgary, Canada; and is now a pastor in Canada. He is co-author, with Owen Strachan of The Grand Design - Male and Female He Made Them.\n\nIn this podcast he talks about his own story and about heroes from church history.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "wYcMkf2rJNU",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/wYcMkf2rJNU/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/wYcMkf2rJNU",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560422136019.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-01-21",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0227961a519e4080891139",
		},
		lastModified: 1560422294403,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d02284d1a519e408089113e",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Mark Jackson and Pete Nicholas",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Mark Jackson and Pete Nicholas (co-author of Virtually Human: Flourishing In A Digital World, IVP 2015) lead Inspire Saint James Clerkenwell, a church planted from All Souls Langham Place and part of the Redeemer City to City Network. \n\nThey talk with us about the church, their own stories, and the people who've inspired them. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "dzAzKAzWMvI",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/dzAzKAzWMvI/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/dzAzKAzWMvI",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560422362262.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-02-04",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d02284d1a519e408089113e",
		},
		lastModified: 1560422477249,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d0229a01a519e4080891143",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Adrian Reynolds",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Adrian Reynolds is Associate National Director of the FIEC (Fellowship of Independent Evangelical Churches). He has worked in business, served in pastoral ministry and used to direct the Evangelical Ministry Assembly. \n\nWe had the privilege of talking with him about his own story and about people who've influenced and inspired him. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "itKKexq2Rec",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/itKKexq2Rec/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/itKKexq2Rec",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560422579155.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-02-25",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d0229a01a519e4080891143",
		},
		lastModified: 1560422816333,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d022acb1a519e4080891148",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Melvyn Bragg and Ben Virgo discuss William Tyndale. The Unbelievable Show.",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Renowned British broadcaster Melvyn Bragg and Ben Virgo of Christian Heritage London joined Justin as guests on Unbelievable. Melvyn talked about why, as a non-believer, he holds the Bible in such high regard. His recent book 'William Tyndale: A Very Brief History’ traces the life and legacy of the reformer William Tyndale whose English translation of the Bible laid the foundation for the King James Version.  ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "Ja5jhSAgWBU",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/Ja5jhSAgWBU/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/Ja5jhSAgWBU",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560422995462.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-04-11",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d022acb1a519e4080891148",
		},
		lastModified: 1560423115427,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d022df71a519e4080891150",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Dick Lucas",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Dick Lucas, Rector Emeritus of St Helen's Bishopsgate, founder of Proclamation Trust and Cornhill Training Course, preacher and Bible commentator, talks about his own story and heroes from church history.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "bbJ5tzqUPdg",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/bbJ5tzqUPdg/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/bbJ5tzqUPdg",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1560423855842.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-06-13",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d022df71a519e4080891150",
		},
		lastModified: 1560461871202,
		dateCreated: 1671487897507,
	},
	{
		_id: "5d1b99b27c437c4f0401e4da",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Dan Strange",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: 'Dan Strange is a thought leader in Christian cultural engagement who has written on the strategic idea of "subversive fulfillment." His recent book "Plugged In" has been praised by Bill Edgar, who says "This gem of a book will be the go-to text for years to come" and Tim Keller, who says "There really is nothing else like this book." \nHis other books include "For Their Rock Is Not As Our Rock" and (with Mike Ovey) "Confident - Why We Can Trust God\'s Word."\nDr Strange is College Director and Lecturer in Culture, Religion and Public Theology at Oak Hill College, London.',
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "mzGnYcID3fU",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/mzGnYcID3fU/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/mzGnYcID3fU",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1562089144798.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-07-02",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5d1b99b27c437c4f0401e4da",
		},
		dateCreated: 1562089906606,
		lastModified: 1562091893554,
	},
	{
		_id: "5dbc9eb27822f961bb35f9e2",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Dan Strange Plugged In book launch - audio now available",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: 'Dr Daniel Strange of Oak Hill Theological College has written Plugged In - a book that helps believers in conversations with non-believing friends by drawing attention to the conversation that\'s already happening. The living God is already revealing himself to a world that is suppressing that truth.\n"There really is nothing like this book" - Tim Keller.\nListen to the full audio from the launch event here.',
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "qXfpSRSY4Ro",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/qXfpSRSY4Ro/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/qXfpSRSY4Ro",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1572642477101.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-11-01",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5dbc9eb27822f961bb35f9e2",
		},
		dateCreated: 1572642482571,
		lastModified: 1572642482569,
	},
	{
		_id: "5df1f8950176327d4afcfed4",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Jeremy Marshall interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Jeremy Marshall, is the author of Beyond the Big C. The former CEO of Credit Suisse and Chairman of C Hoare, he was given an 18 month terminal diagnosis for cancer six years ago and has spent much of those six years talking about the surpassing worth of knowing Jesus Christ.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "pVAkO5qWBFY",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/pVAkO5qWBFY/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/pVAkO5qWBFY",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1576173549940.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2019-12-12",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5df1f8950176327d4afcfed4",
		},
		dateCreated: 1576138901860,
		lastModified: 1576173552904,
	},
	{
		_id: "5e46b25761eeda6a1e9f3cd7",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Stephen Clark",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Stephen Clark teaches at London Seminary; is pastor at Freeschool Court Evangelical Church, Bridgend; and has published two books with IVP.\nIn this episode he shares golden gospel details from his life and church history. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "HwoECK5iSKI",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/HwoECK5iSKI/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/HwoECK5iSKI",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1581689566526.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-02-14",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5e46b25761eeda6a1e9f3cd7",
		},
		dateCreated: 1581691479962,
		lastModified: 1581691479960,
	},
	{
		_id: "5e84cdcb61eeda6a1e9f3d21",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Peter Leithart interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: 'Peter Leithart is a theologian and the author of dozens of books - including the recently acclaimed two volume Revelation commentary in the ICC series for T&T Clark ("an immensely important work of theology. He has not just interpreted Revelation; he has contributed to the ongoing project of knowing God in Christ. And while he writes at an academic level, he looks to the pastoral implications. For him, all theology is pastoral." - TGC). He is President of the Theopolis Institute. \n\nIn this episode we talk about his own story: his upbringing, influence of Westminster Seminary, and about Augustine; as well as teasing out his thought and advice for the church in our time.',
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "vd3uzox4N5Y",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/vd3uzox4N5Y/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/vd3uzox4N5Y",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1585761712297.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-04-01",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5e84cdcb61eeda6a1e9f3d21",
		},
		dateCreated: 1585761739236,
		lastModified: 1602576244732,
	},
	{
		_id: "5ead143b2cad880c03f329cf",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Andrew Sach interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Andrew Sach (PhD University of York) is a leader at Grace Church Greenwich, he teaches at the Cornhill Training Course, and has co-written several books including (with Mike Ovey and Steve Jeffery) Pierced for Our Transgressions.\nWe talked with him about his conversion, the writing of Pierced for Our Transgressions, and the enduring power of heroes from history.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "gseSz0HpmlY",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/gseSz0HpmlY/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/gseSz0HpmlY",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1588400764636.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-05-02",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5ead143b2cad880c03f329cf",
		},
		dateCreated: 1588401211170,
		lastModified: 1590072860988,
	},
	{
		_id: "5f579a8f1cd55e2a19ed54ca",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "David Jackman interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "David Jackman served with UCCF in London, was taught by J I Packer and Alec Motyer at Trinity College Bristol and was pastor Above Bar Church in Southampton before becoming Director of the Cornhill Training Course in London. \n\nHe has written numerous bible commentaries including the edition on the Epistles of John in the IVP Bible Speaks Today series, and several other books. He speaks and teaches nationally and internationally, especially on the subject of preaching.\n\nIn this episode we talk about his own fascinating story, the influence of John Calvin and Francis Shaeffer, and the personal influence on him of John Stott, Jim Packer, Dick Lucas, Alec Motyer and his own grandfather.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "b1liEnWiOWo",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/b1liEnWiOWo/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/b1liEnWiOWo",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1599578033265.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-09-08",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5f579a8f1cd55e2a19ed54ca",
		},
		dateCreated: 1599576719616,
		lastModified: 1599578253051,
	},
	{
		_id: "5f84ac831cd55e2a19ed54f4",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Guy Miller interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Guy Miller leads the Commission group of churches - one of the spheres of churches that came out of the Newfrontiers family in 2011. With churches on four continents it seeks to establish believers in the gospel of Jesus Christ, equip them for his service and plant more churches to do the same.\n\nWe had the pleasure of learning more about Guy himself, his testimony, and people who've influenced him at Westminster Chapel, one of the churches in the Commission family. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "oGQlcMEpM80",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/oGQlcMEpM80/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/oGQlcMEpM80",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1602530430844.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-10-12",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5f84ac831cd55e2a19ed54f4",
		},
		dateCreated: 1602530435609,
		lastModified: 1602530435607,
	},
	{
		_id: "5fb42ca11cd55e2a19ed54fd",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Kenneth Brownell interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Ken Brownell, pastor of ELT Baptist Church, author and lecturer in Church History at London Seminary is also a trustee of Christian Heritage London. We had a great time talking with him about the potency of church history as an encouragement, guide and stimulus for believers.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "qW177VutbkU",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/qW177VutbkU/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/qW177VutbkU",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1605643409897.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-11-17",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5fb42ca11cd55e2a19ed54fd",
		},
		dateCreated: 1605643425611,
		lastModified: 1605643528792,
	},
	{
		_id: "5fc91b851cd55e2a19ed5509",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Tony Lane interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Tony Lane studied at Oxford and Cambridge and has taught at Oak Hill Theological College and London School of Theology. He has written a number of books, most recently the acclaimed Sin and Grace, Evangelical Soteriology in Historical Perspective (IVP). \n\nWe had an excellent time hearing his own story, stories of his influences and his insight for our own time.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "7eUPOHyZN6M",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/7eUPOHyZN6M/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/7eUPOHyZN6M",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1607015294652.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2020-12-03",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "5fc91b851cd55e2a19ed5509",
		},
		dateCreated: 1607015301291,
		lastModified: 1607946625751,
	},
	{
		_id: "6001b27659154f4d5917e4f5",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Jennie Pollock interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Jennie Pollock, Associate Head of Public Policy at the Christian Medical Fellowship, is a writer, editor, blogger and member of Grace London. \n\nShe has just published her first book: If Only - Finding joyful contentment in the face fo lack and longing. We had an excellent time hearing her own story, stories of people who've inspired her, and  insights on what it is to live by faith. https://youtu.be/e1GhgUW6FXI",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "e1GhgUW6FXI",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/e1GhgUW6FXI/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/e1GhgUW6FXI",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1610790468865.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-01-15",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "6001b27659154f4d5917e4f5",
		},
		dateCreated: 1610723958018,
		lastModified: 1610790474176,
	},
	{
		_id: "607680b26c9245516d81d838",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Ian Dobbie interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Ian Dobbie, grandson on William Dobbie of Malta and a man with a sense of history, has lived a fascinating life considering and applying the implications of a legacy built on the grace of God in Christ. \nWe had an outstanding time talking about the history of his family, his own story and about heroes of the gospel of Jesus Christ. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "ZqZ5RPDIWqc",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/ZqZ5RPDIWqc/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/ZqZ5RPDIWqc",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1618378845921.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-04-14",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "607680b26c9245516d81d838",
		},
		dateCreated: 1618378930803,
		lastModified: 1618378930801,
	},
	{
		_id: "6099b1016c9245516d81d841",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Neil Powell interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Neil Powell, co-author of Together for the City (IVP, 2019) began the 2020 Birmingham project with the goal of planting 20 churches in Birmingham by 2020, in collaboration with other churches. Having done this, he is moving to London to start The London Project, facilitating, enabling and mobilising relationships between gospel churches in London. \nWe had an excellent time talking about his own story, his heroes, and how, through local churches, the gospel might be presented to London. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "_8zp6yTGqIk",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/_8zp6yTGqIk/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/_8zp6yTGqIk",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1620685053081.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-05-10",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "6099b1016c9245516d81d841",
		},
		dateCreated: 1620685057169,
		lastModified: 1620685057168,
	},
	{
		_id: "611c06541bdbf27de8ead78d",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Terry Virgo on God's Treasured Possession",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "God uses stories to teach his people: his word and church history are full of them. The story of Moses teaches a huge amount about leadership - and in his new book, God's Treasured Possession, Terry Virgo draws out precious and essential lessons on this oh so neglected but oh so necessary subject. \n\nTerry Virgo began the New Frontiers group of churches which now have over 2,000 churches internationally. In this episode he is interviewed by his son, Ben Virgo. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "D0Jri1w7kAk",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/D0Jri1w7kAk/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/D0Jri1w7kAk",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1629226577499.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-08-17",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "611c06541bdbf27de8ead78d",
		},
		dateCreated: 1629226580667,
		lastModified: 1629232033573,
	},
	{
		_id: "61451c2c1bdbf27de8ead7ab",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Kevin Belmonte interview ",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Kevin Belmonte is an award winning biographer of Wilberforce, Moody, Chesterton and most recently William Borden - and was our guest on the podcast. His book on Wilberforce has been used in character studies at Harvard University and he was lead historical consultant for the film Amazing Grace. \n\nIt was a thrilling time sharing our delight in the stories because of our shared conviction that history hasn't finished. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "D5dsEnfBrp8",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/D5dsEnfBrp8/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/D5dsEnfBrp8",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1631919130454.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-09-17",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "61451c2c1bdbf27de8ead7ab",
		},
		dateCreated: 1631919148505,
		lastModified: 1631919148504,
	},
	{
		_id: "617715e210bb16042b93c92f",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Joel Morris interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Dr. Joel Morris has travelled stormy oceans, got a doctorate in South Korea, plays electric guitar, writes books and is Executive Director of Union. We had an excellent time talking with him and getting advice on what to do in a storm at sea. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "VuknxPCLmi4",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/VuknxPCLmi4/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/VuknxPCLmi4",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1635194334657.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-10-25",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "617715e210bb16042b93c92f",
		},
		dateCreated: 1635194338251,
		lastModified: 1635194338249,
	},
	{
		_id: "6182490810bb16042b93c954",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Dan Strange's Making Faith Magnetic book launch.",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "The gospel is the answer, but is anyone asking the question in our time?? The Bible says that YES, the very things for which our generation YEARNS are answered in the gospel. Dan Strange has written another outstanding work helping the church to engage people with the good news. \nHear the book launch here.  ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "DOnlSK4CKp4",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/DOnlSK4CKp4/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/DOnlSK4CKp4",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1635928322408.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-11-03",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "6182490810bb16042b93c954",
		},
		dateCreated: 1635928328995,
		lastModified: 1636197879623,
	},
	{
		_id: "61b2637910bb16042b93c9b0",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Al Barth interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Al Barth is a servant of the church of God known the world over for his graciousness and wisdom. He has served with Tim Keller as Executive Director for Redeemer City to City since its founding, overseeing its work in Europe, the Middle East and North Africa. He has lately taken on the position of Executive Director of the newly emerging fellowship of churches known as City to City North America.\n\nWe had a fantastic time getting to know him and hearing about his heroes.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "Yz7QleEONew",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/Yz7QleEONew/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/Yz7QleEONew",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1639080820649.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2021-12-15",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "61b2637910bb16042b93c9b0",
		},
		dateCreated: 1639080825730,
		lastModified: 1639643584619,
	},
	{
		_id: "61df635ed1f28a66d956be9c",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Dustin Benge interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Dustin Benge is a man of gospel clarity and gospel conviction. Professor of Biblical Spirituality and Historical Theology at Southern Baptist Theological Seminary and VP of Communications, he's also the author of The Loveliest Place.\n\nDustin's clarity and convictions have been fed and watered by the example and works of many believers from church history and we had a wonderful time, having taken him on a Christian Heritage London walk through the City of London, talking with him about their stories and his own story. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "mDUhkFrMZDk",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/mDUhkFrMZDk/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/mDUhkFrMZDk",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1642029906154.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-01-12",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "61df635ed1f28a66d956be9c",
		},
		dateCreated: 1642029918161,
		lastModified: 1642029918159,
	},
	{
		_id: "6201a3c3d1f28a66d956bf0f",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Chris Green podcast",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Where are the leaders? WE NEED LEADERS.\n\nChris Green knows a few things about leadership: former Vice Principal of Oak Hill Theological College, vicar of St James, Muswell Hill, a large London church and a teacher of teachers. He's lately written The Gift, How Your Leadership Can Serve Your Church.\n\nWe had a superb time talking about leadership, leaders who've inspired him and about *serving* as a leader.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "jwPoz2PHtvM",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/jwPoz2PHtvM/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/jwPoz2PHtvM",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1644274622684.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-02-07",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "6201a3c3d1f28a66d956bf0f",
		},
		dateCreated: 1644274627427,
		lastModified: 1644274627424,
	},
	{
		_id: "62194ad2d1f28a66d956bf3f",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Andrew Sach and Jonathan Gemmell book launch - Are You 100% Sure You Want To Be An Agnostic?",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "You’re not sure what you think about God. You’re not an atheist – you’re not that confident of his non-existence. You’re not a Christian or a Muslim, though you’ve got nothing against either of them. You prefer to identify as a humble agnostic. Some would say you’re sitting on the fence, but why not? It’s a comfortable enough place to be. Why can’t we all just admit we don’t know?\n\nYet sometimes you do have questions. Where did we come from? What happens when we die? Can anyone make sense of all the suffering in the world? What’s it all for? You wouldn’t mind answers to some of them, as long as no one tried to brainwash you. You’re not 100% sure that you enjoy not being sure.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "sLaNIDw-8q4",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/sLaNIDw-8q4/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/sLaNIDw-8q4",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1645824575445.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-02-25",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "62194ad2d1f28a66d956bf3f",
		},
		dateCreated: 1645824722586,
		lastModified: 1645824722584,
	},
	{
		_id: "622679b5d1f28a66d956bf73",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Michael McMullen interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Michael McMullen, Professor of Church History at Midwestern Baptist Theological Seminary and Editor of the Midwestern Journal of Theology, is behind previously unpublished works by Robert Murray M'Cheyne, Jonathan Edwards and now the previously unpublished Spiritual Journals of William Wilberforce.\n\nThis most recent book has been described as one of the most important publications from the last ten years, revealing the heart of the man whose personal walk with the risen Christ was the root of his long but ultimately victorious battle for the abolition of the slave trade.\n\nWe had an outstanding time talking with Michael about his influences, their stories and about his own story. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "tAfA-V_1yDg",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/tAfA-V_1yDg/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/tAfA-V_1yDg",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1646688678053.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-03-07",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "622679b5d1f28a66d956bf73",
		},
		dateCreated: 1646688693397,
		lastModified: 1646688693394,
	},
	{
		_id: "622f9938d1f28a66d956bf84",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "James Eglinton interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "James Eglinton has done outstanding work in our time drawing attention to the work of Herman Bavinck. The author of the acclaimed Bavinck: A Critical Biography, he has introduced a generation to the life and times of a luminous thinker whose God-centred theology, only recently made available in English, is now stimulating, provoking and encouraging believers outside of Holland for the first time.\n\nWe had a fantastic time talking with James about his own story, about his experience of working across cultures, and about Bavinck.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "sPL-F5hXHoQ",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/sPL-F5hXHoQ/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/sPL-F5hXHoQ",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1647286579248.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-03-14",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "622f9938d1f28a66d956bf84",
		},
		dateCreated: 1647286584428,
		lastModified: 1647286584425,
	},
	{
		_id: "62423bccd1f28a66d956bfa9",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Sharon James book launch",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Sharon James studied history at Cambridge and theology in Toronto and Wales, and now brings piercing, prophetic insight to the extraordinary challenges of our culture through her work at The Christian Institute. \n\nSharon has lately written The Lies We Are Told, The Truth We Must Hold, in which she looks at the thought behind the cultural challenges of our moment and how they are answered in the gospel. Conrad Mbewe said of the book “The panoramic view is breath-taking! It is like standing on the sun and seeing all the planets in the solar system going around in beautiful symmetry. The confusion turns to picturesque order.” Wayne Grudem called it “a remarkable book”. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "nY26iAD8fGA",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/nY26iAD8fGA/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/nY26iAD8fGA",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1648507512872.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-03-29",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "62423bccd1f28a66d956bfa9",
		},
		dateCreated: 1648507852891,
		lastModified: 1648507852879,
	},
	{
		_id: "62552827d1f28a66d956bfbf",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Mez McConnell interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Mez McConnell is senior pastor of Niddrie Community Church in Edinburgh, Scotland, founder of the 20 Schemes church planting network, and author of several books, most recently The Least, The Last and The Lost. \n\nIt was a great privilege to sit with him, hear his story, talk about his influences and be inspired by his example of faithful, bible-established, gospel-inspired obedience. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "s_pLPieiKOo",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/s_pLPieiKOo/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/s_pLPieiKOo",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1649748003780.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-04-12",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "62552827d1f28a66d956bfbf",
		},
		dateCreated: 1649748007075,
		lastModified: 1649748007074,
	},
	{
		_id: "6266bd95d1f28a66d956bfe6",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Alun Ebenezer interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Alun Ebenezer is the founding headmaster of Fulham Boys School, a centre of excellence in central London. Here boys are taught from an ethos of resilience, kindness and a can do attitude - an ethos that is geared towards boys, which nurtures enterprise - business, social and personal - and is built upon the Christian Faith. It's an ethos which relies on strong leadership, is committed to firm discipline, academic excellence, a love of sport and an appreciation of the arts.\n\nIt was a privilege to talk with Alun, a leader in our time, about his own story of putting his faith in the Lord Jesus Christ, his own heroes and the story of a remarkable work of faith in central London in our time. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "rhsdl0XyGR0",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/rhsdl0XyGR0/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/rhsdl0XyGR0",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1650900355838.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-04-25",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "6266bd95d1f28a66d956bfe6",
		},
		dateCreated: 1650900373856,
		lastModified: 1650900373853,
	},
	{
		_id: "627a079fd1f28a66d956c031",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Iain Murray interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "While he was assistant to Dr Martyn Lloyd-Jones at Westminster Chapel in London, Iain Murray was asked by the Doctor to give some lectures on church history. And so began a fascination with church history which would flourish into a ministry which would bless the body of Christ internationally: the Banner of Truth publishing house.\n\nIf you have heard of Charles Spurgeon, Jonathan Edwards, John Owen, J C Ryle, Richard Sibbes or any of the English Puritans it is likely because of the Banner of Truth. The Banner of Truth has reprinted their works for decades, as well as the works of Dr Lloyd-Jones, Sinclair Ferguson and other contemporary writers. \n\nIain Murray himself has written many highly acclaimed biographies, including works on Jonathan Edwards, Charles Spurgeon and John Wesley, as well as the authorised biography of Dr Martyn Lloyd-Jones himself. \n\nIt was a great privilege to sit down with Iain, to hear his story, and to talk about people who've inspired him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "BNKdIm7xJYk",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/BNKdIm7xJYk/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/BNKdIm7xJYk",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1652162929059.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-05-10",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "627a079fd1f28a66d956c031",
		},
		dateCreated: 1652164511740,
		lastModified: 1652164511739,
	},
	{
		_id: "628c060ad1f28a66d956c066",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Chris Larson interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Chris Larson is President and CEO of Ligonier Ministries, which began as the ministry of R C Sproul. R C's ministry has established and inspired believers internationally for generations - his great book The Holiness of God being a watershed text for many. \n\nLigonier established a number of teaching fellowships such as Sinclair Ferguson and Stephen Nichols, and has continued to serve the church internationally through resources and conferences. Thus following R C's death in 2017 Ligonier has continued, under the leadership of Chris Larson, to be a potent and strategic asset in the worldwide church.\n\nWe had a superb day with Chris lately walking through London's church history and talking with him about heroes, strategy and effectiveness on the podcast.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "g-UZrLmLIxk",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/g-UZrLmLIxk/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/g-UZrLmLIxk",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1653342077101.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-05-24",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "628c060ad1f28a66d956c066",
		},
		dateCreated: 1653343754212,
		lastModified: 1653343754210,
	},
	{
		_id: "62a348abafbe717a380f1f65",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Dean Inserra interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Dean Inserra planted City Church Tallahassee 15 years ago and is passionate about reaching the city of Tallahassee with the Gospel, to see a *worldwide* impact made for Jesus. The congregation frequently sees thousands in attendance and is known for its emphasis on local equipping and ministry.\n\nDean has written several books, most recently Pure, published by Moody Publishers. \n\nWe had an outstanding time talking about his story, his influences and about the potent ministry of the local church. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "EGVOOeBghcw",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/EGVOOeBghcw/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/EGVOOeBghcw",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1654868122068.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-06-10",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "62a348abafbe717a380f1f65",
		},
		dateCreated: 1654868139433,
		lastModified: 1654868139431,
	},
	{
		_id: "637c9e897ad8a878056ccdb0",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Tim Dieppe interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Tim Dieppe is someone of whom you’ve likely heard but would like to learn more: he is Head of Public Policy at Christian Concern, and is engaging - boldly, wisely and articulately - with many of the great challenges which Christians are finding in the work place, schools and wider society at the present time. It was excellent to sit down with him and hear his own story and stories of people who’ve inspired him.",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "jUcmJttzNEs",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/jUcmJttzNEs/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/jUcmJttzNEs",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1669111429006.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-11-22",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "637c9e897ad8a878056ccdb0",
		},
		dateCreated: 1669111433514,
		lastModified: 1669111433512,
	},
	{
		_id: "638de7cb7ad8a878056ccdd9",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Allen McClymont interview",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Allen McClymont is a typical Londoner: born in Malaysia he grew up in New Zealand and has taught New Testament Greek in Malaysia! For nearly twenty years he's worked with OMF, the missionary society begun by J Hudson Taylor. \nWe had a great time talking about the potential and opportunity of international mission and how the roots of his passion to serve and establish people in the gospel were fed. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "qnpJwDKTOCg",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/qnpJwDKTOCg/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/qnpJwDKTOCg",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1670244296077.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-12-05",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "638de7cb7ad8a878056ccdd9",
		},
		dateCreated: 1670244299256,
		lastModified: 1670246180992,
	},
	{
		_id: "639920b07ad8a878056ccdea",
		__v: 0,
		data: {
			sections: [],
			id: "episode",
			title: "Episode - Podcast",
			fields: [
				{
					name: "title",
					label: "Title",
					type: "text",
					value: "Bill Edgar interview: A Supreme Love",
					placeholder: "Enter episode title",
					required: true,
				},
				{
					name: "desc",
					label: "Description",
					type: "textarea",
					value: "Bill Edgar, who we have previously interviewed on the Christian Heritage London podcast, taught Apologetics at Westminster Theological Seminary from 1989 until summer 2022, and has now written a book on a subject dear to his heart: jazz. In A Supreme Love, Edgar considers the context from which this unique art form came in American history, the pioneers who defined it and the transcendent nature of its beauty. It's a fascinating introduction to, and commentary on, a musical genre which, he argues, can only be appreciated in light of the gospel of Jesus Christ. \n\nWe had an excellent time talking with him about it on the Christian Heritage London podcast. ",
					placeholder: "Enter a brief description",
					required: true,
				},
				{
					name: "ytid",
					label: "YouTube Video ID",
					type: "ytid",
					value: "RKvtcqMwavA",
					placeholder: "e.g. Ja5jhSAgWBU",
					ext: {
						image: "https://img.youtube.com/vi/RKvtcqMwavA/hqdefault.jpg",
						embed: "https://www.youtube.com/embed/RKvtcqMwavA",
					},
					required: true,
				},
				{
					name: "audio",
					label: "Audio",
					type: "audio",
					value: "https://s3.eu-west-2.amazonaws.com/chlpodcasts/1670979642703.mp3",
					ext: { length: 1 },
				},
				{
					name: "pubDate",
					label: "Publish Date",
					type: "date",
					value: "2022-12-14",
					placeholder: "Enter publish date",
					required: true,
				},
			],
			_id: "639920b07ad8a878056ccdea",
		},
		dateCreated: 1670979760386,
		lastModified: 1670979760384,
	},
];
